-- TouristTurkey — başlangıç verisi
-- schema.sql çalıştıktan SONRA bunu çalıştırın.

insert into suppliers (id,name,cat,wa,pin) values
  ('sup1','Mavi Yıldız Tekne','Tekne & Boğaz','+90 542 000 10 01','1111'),
  ('sup2','Elif Rehberlik','Rehberli turlar','+90 542 000 10 02','2222'),
  ('sup3','Nova Transfer','Transfer & araç','+90 542 000 10 03','3333'),
  ('sup4','Çınar Hamamı','Hamam & spa','+90 542 000 10 04','4444'),
  ('sup5','Bilet Noktası','Müze & bilet','+90 542 000 10 05','5555'),
  ('sup6','Anadolu Seyahat','Şehir dışı','+90 542 000 10 06','6666') on conflict (id) do nothing;

insert into concierges (id,name,desk,wa,pin) values
  ('c1','Emre A.','Vista Travel Desk','+90 532 000 00 01','1111'),
  ('c2','Selin K.','Bosphorus Concierge','+90 533 000 00 02','2222'),
  ('c3','Kaan T.','Court Tourism','+90 535 000 00 03','3333') on conflict (id) do nothing;

insert into hotels (slug,name,district,rooms,accent,concierge_id,split,cover) values
  ('otelpera','Pera Vista Hotel','Beyoğlu',62,'#1E9C9F','c1',0.5,'perahotel'),
  ('galatahouse','Galata House','Karaköy',38,'#B8862F','c2',0.6,'galatahotel'),
  ('sultancourt','Sultan Court Suites','Sultanahmet',84,'#C4604B','c3',0.5,'sultanhotel') on conflict (slug) do nothing;

insert into products (id,slug,cat,supplier_id,title,short,long,list,net,unit,dur,meet,inc,exc,photo,cap,rank) values
  ('p01','bogaz-aksam-yemegi-turu','bogaz','sup1','Boğaz''da Akşam Yemeği Turu & Show','Işıklı Boğaz manzarası, Türk mutfağı ve canlı gösteri. Pencere kenarı masa opsiyonlu.','Akşam saatlerinde Boğaz''a açılan bu tur, İstanbul''un en çok satan tek ürünü. Fatih Sultan Mehmet Köprüsü, Kız Kulesi ve Sultanahmet siluetinin ışıklı hali suyun üzerinden izleniyor. Menüde mezeler, ana yemek ve tatlı; eşliğinde canlı müzik ve dans gösterisi yer alıyor. Oteldan alma opsiyonu mevcut.',65,46,'kişi','3 saat','Otelden alım veya Kabataş','["Tekne turu","Akşam yemeği","Canlı gösteri","Otelden alım (opsiyonlu)"]'::jsonb,'["Alkollü içecekler","Bahşiş"]'::jsonb,'bosphorusdinner',40,1),
  ('p02','ayasofya-sultanahmet-yerebatan','kultur','sup5','Ayasofya + Sultanahmet + Yerebatan Kombine','Üç ikonik yapı, tek bilette. Kuyruk atlamalı giriş ve sesli rehber dahil.','İstanbul''un en yoğun üç noktası tek pakette. Ayasofya''da yabancı ziyaretçiler için ayrı giriş kullanılıyor, Yerebatan Sarnıcı''nda zaman dilimli bilet ile kuyruk atlanıyor. Sultanahmet Camii ziyareti namaz saatlerine göre planlanıyor. Sesli rehber 8 dilde.',79,58,'kişi','3 saat','Sultanahmet Meydanı','["3 mekân girişi","Kuyruk atlama","Sesli rehber","Baş örtüsü"]'::jsonb,'["Ulaşım","Yeme-içme"]'::jsonb,'hagiasophia',60,2),
  ('p03','best-of-istanbul-ozel-tur','kultur','sup2','Best of Istanbul — 1 Günlük Özel Rehberli Tur','Ruhsatlı özel rehberle Eski Şehir''in tamamı. Otelden alma dahil.','Ayasofya, Sultanahmet, Topkapı, Hipodrom ve Kapalıçarşı tek günde. Özel tur olduğu için tempo ve rota tamamen size göre ayarlanıyor. Ruhsatlı rehber zorunluluğu bu üründe karşılanıyor. 2 ve 3 günlük uzatma opsiyonu mevcut.',185,138,'grup','7 saat','Otel lobisi','["Ruhsatlı özel rehber","Otelden alım","Rota planlaması"]'::jsonb,'["Müze biletleri","Öğle yemeği"]'::jsonb,'istanbultour',8,3),
  ('p04','topkapi-harem-rehberli','kultur','sup5','Topkapı Sarayı & Harem — Rehberli, Hızlı Geçiş','Osmanlı sarayının tamamı, Harem dahil. Bilet ve öncelikli giriş içeride.','Topkapı Sarayı''nın avluları, Kutsal Emanetler bölümü ve ayrı bilet gerektiren Harem dairesi tek turda geziliyor. Hızlı geçiş sayesinde sezonda 40-60 dakikalık kuyruk atlanıyor. Salı günleri kapalı.',89,66,'kişi','3 saat','Topkapı ana kapı','["Saray + Harem bileti","Hızlı geçiş","Rehber"]'::jsonb,'["Ulaşım"]'::jsonb,'topkapi',30,4),
  ('p05','gun-batimi-yat-turu','bogaz','sup1','Gün Batımı Küçük Grup Yat Turu','Kalabalık olmayan yatta, ikramlı, iki saatlik Boğaz turu. Özel opsiyonu var.','Maksimum 12 kişilik yatla Boğaz''ın iki yakası. Rumeli Hisarı, Ortaköy ve Kız Kulesi rotası. İkramlar ve soft içecekler dahil. Tekneyi tamamen özel kiralama opsiyonu ayrıca sunuluyor — çift ve kutlamalar için en çok tercih edilen ürün.',120,88,'kişi','2 saat','Kabataş İskele','["Yat turu","İkramlar","Soft içecek"]'::jsonb,'["Alkol","Transfer"]'::jsonb,'yachtbosphorus',12,5),
  ('p06','yerebatan-hizli-giris','kultur','sup5','Yerebatan Sarnıcı — Hızlı Giriş','Zaman dilimli bilet, kuyruksuz giriş, sesli rehber.','Bizans döneminden kalan sarnıç, İstanbul''un en yoğun kapalı mekânı. Zaman dilimli bilet sistemi sayesinde belirlenen saatte doğrudan giriş yapılıyor. Işık ve ses düzenlemesiyle akşam ziyareti ayrıca öneriliyor.',39,28,'kişi','1 saat','Sarnıç giriş kapısı','["Bilet","Kuyruk atlama","Sesli rehber"]'::jsonb,'[]'::jsonb,'cistern',80,6),
  ('p07','ozel-turk-hamami','hamam','sup4','Özel Türk Hamamı, Kese & Masaj','Tarihi hamamda geleneksel ritüel. Özel bölüm opsiyonlu.','Mermer göbek taşında geleneksel kese ve köpük masajı, ardından yağ masajı. Peştemal, havlu ve terlik dahil. Çiftler için özel bölüm opsiyonu mevcut. Otelden transfer eklenebilir.',85,62,'kişi','90 dk','Hamam girişi (Eski Şehir)','["Kese","Köpük masajı","Yağ masajı","Peştemal & havlu"]'::jsonb,'["Bahşiş","Transfer"]'::jsonb,'turkishbath',20,7),
  ('p08','ist-havalimani-transfer','transfer','sup3','IST Havalimanı → Otel Özel Transfer','Mercedes sınıfı araç, isimli karşılama, 60 dakika ücretsiz bekleme.','İstanbul Havalimanı''ndan otele kapıdan kapıya özel transfer. Şoför isimli tabelayla çıkışta karşılıyor, 60 dakikaya kadar ücretsiz bekliyor. Uçuş takibi yapılıyor, rötarda ek ücret alınmıyor. Taksi kuyruğu ve pazarlık derdi ortadan kalkıyor.',55,39,'araç','60 dk','Geliş katı, isimli karşılama','["Özel araç","Karşılama","60 dk bekleme","Uçuş takibi"]'::jsonb,'["Ek durak"]'::jsonb,'airporttransfer',15,8),
  ('p09','eski-sehir-yuruyus-turu','kultur','sup2','Eski Şehir Yürüyüş Turu','Küçük grup, ruhsatlı rehber, otelden buluşma. İlk gün için ideal.','Şehre ilk gelenler için tasarlanmış 3 saatlik yürüyüş. Sultanahmet çevresi, Hipodrom, Mısır Çarşısı ve ara sokaklar. Rehber yerel öneriler, ulaşım kartı ve güvenli restoran listesi de paylaşıyor — misafirin geri kalan günlerini planlaması kolaylaşıyor.',45,32,'kişi','3 saat','Otel lobisi veya Sultanahmet','["Ruhsatlı rehber","Küçük grup","Şehir önerileri"]'::jsonb,'["Müze girişleri"]'::jsonb,'oldtownwalk',15,9),
  ('p10','kapadokya-2-gun-balon','ozel','sup6','Kapadokya 2 Gün — Uçuş & Mağara Otel (Balon Opsiyonlu)','İstanbul''dan uçuşlu paket. Mağara otelde konaklama, balon eklenebilir.','Gidiş-dönüş uçak, havaalanı transferleri, mağara otelde 1 gece konaklama ve iki gün boyunca Kuzey-Güney Kapadokya turları. Sıcak hava balonu opsiyonel olarak ekleniyor; balon uçuşları hava şartlarına ve günlük kotaya bağlı, iptalde ücret iade ediliyor. En yüksek sepetli ürün.',495,405,'kişi','2 gün','Otelden alım','["Gidiş-dönüş uçuş","Mağara otel","Transferler","2 gün tur","Kahvaltı"]'::jsonb,'["Balon uçuşu (opsiyon)","Öğle yemekleri"]'::jsonb,'cappadocia',16,10),
  ('p11','helikopter-turu','ozel','sup1','İstanbul Helikopter Turu — 20 Dakika','Boğaz ve tarihi yarımada üstünde alçak irtifa uçuş. Transfer dahil.','Heliporta özel transfer, güvenlik brifingi ve 20 dakikalık panoramik uçuş. Boğaz köprüleri, Adalar ve tarihi yarımada rotası. Hava muhalefetinde tarih ücretsiz değiştiriliyor.',420,345,'kişi','20 dk + transfer','Otelden alım','["Uçuş","Transfer","Sigorta","Brifing"]'::jsonb,'[]'::jsonb,'helicopter',5,11),
  ('p12','karakoy-lezzet-yuruyusu','lezzet','sup2','Karaköy & Balat Lezzet Yürüyüşü','7 durak, tüm tadımlar dahil. Turist menülerinin dışında gerçek yerler.','Karaköy''den başlayıp Balat''a uzanan 3 saatlik yürüyüş. Balık ekmek, esnaf lokantası, tarihi muhallebici ve kahveci durakları. Tüm tadımlar fiyata dahil; misafir doyarak ayrılıyor. Küçük grup, maksimum 10 kişi.',78,56,'kişi','3 saat','Karaköy Meydanı','["7 durak","Tüm tadımlar","Rehber"]'::jsonb,'["Alkol"]'::jsonb,'streetfood',10,12),
  ('p13','restoran-rezervasyonu','lezzet','sup2','Restoran Rezervasyonu','Dolu görünen restoranlarda masa. Misafire ücretsiz.','Boğaz manzaralı teraslar, Michelin listesindeki mekânlar ve mahalle esnaf lokantaları dahil geniş bir ağ. Özel istekler (doğum günü, manzara masası, diyet) restorana önceden iletiliyor. Misafirden ücret alınmıyor.',0,0,'','—','Restoranda','["Masa ayırtma","Özel not iletimi"]'::jsonb,'["Hesap"]'::jsonb,'restaurant',99,13),
  ('p14','soforlu-arac-4-saat','transfer','sup3','Şoförlü Araç — 4 Saat','Saatlik özel araç ve şoför. İstediğiniz rota, beklemeli.','Alışveriş, klinik randevusu, iş görüşmesi veya kendi rotanız için saatlik araç. Şoför bekliyor, rota tamamen size ait. İngilizce konuşan şoför opsiyonu mevcut.',125,92,'araç','4 saat','Otel lobisi','["Araç","Şoför","Yakıt","Bekleme"]'::jsonb,'["Otopark","Giriş ücretleri"]'::jsonb,'chauffeur',10,14),
  ('p15','adalar-tekne-turu','bogaz','sup1','Adalar Tekne Turu','Büyükada rotası, öğle yemeği dahil. Şehirden bir gün kaçış.','Kabataş''tan kalkan tekneyle Büyükada ve Heybeliada. Adada serbest zaman, fayton yerine bisiklet veya yürüyüş önerisi. Teknede öğle yemeği servis ediliyor.',95,70,'kişi','6 saat','Kabataş','["Tekne","Öğle yemeği","Rehber"]'::jsonb,'["Bisiklet kiralama"]'::jsonb,'princesislands',35,15),
  ('p16','sema-toreni','ozel','sup5','Sema Töreni — Rezerve Koltuk','Galata Mevlevihanesi''nde geleneksel tören. Ön sıra garantili.','Haftanın belirli günlerinde düzenlenen sema törenine rezerve koltuklu giriş. Tören öncesi kısa bilgilendirme yapılıyor. Fotoğraf kuralları rehber tarafından aktarılıyor.',42,30,'kişi','1 saat','Galata Mevlevihane','["Rezerve koltuk","Bilgilendirme"]'::jsonb,'[]'::jsonb,'dervish',25,16) on conflict (id) do nothing;

-- Önümüzdeki 60 gün için müsaitlik satırları
insert into availability (product_id, date, cap, booked, closed)
select p.id, d::date, p.cap, 0, false
from products p, generate_series(current_date, current_date + interval '60 days', interval '1 day') d
on conflict (product_id, date) do nothing;

